### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by IAINATDBI** [triton-inference-server/triton_cli#46]
Looking forward to using this repo.

Ran into an issue with the older style authentication with the git clone command.

`git clone git@github.com:triton-inference-server/triton_cli.git`

This did not work. The following did:

`git clone https://github.com/triton-inference-server/triton_cli.git`

Cheers

**Comment by rmccorm4** [comment]
Hi @IAINATDBI, can you clarify the error you got for the `git clone git@github.com` case? I believe this route is intended for SSH clones which expect you have a properly authenticated SSH key setup and isn't unique to this repository specifically.

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey
