### ISSUE TITLE
Support for "chat" variant of Llama-2-7b model

### ISSUE THREAD

**Issue by IAINATDBI** [triton-inference-server/triton_cli#48]
Successfully ran inference with llama-2-7b. Can you confirm it's the llama2-7b-hf model that is pulled? From the logs it looks like it pulled that one from my cache.

Would the "chat" model not be better for a conversational inference experience? Can you configure what variant is pulled or is it "hard-coded" right now?

Cheers

**Comment by IAINATDBI** [comment]
Hi @rmccorm4, @fpetrini15  - thank you for taking the time for the detailed discussion(s). I've been using Triton for a bit now and its been performing well, so this CLI addition is really great to hear.

I'm keen to use the chat variant so that I can get responses that make sense. Looking forward to hearing about great things to come with Triton!

Cheers

**Comment by rmccorm4** [comment]
Thanks @IAINATDBI, we've marked down a feature request to expand the llama model support for TRT-LLM to be a bit more generic/flexible. I'll modify the title of the issue to better reflect that and keep it open.

**Comment by IAINATDBI** [comment]
HI @rmccorm4  - I tried the vLLM approach as described above and I'm getting an error  during `triton start` it looks like a cuda memory issue and it advises increasing `gpu_memory_utilization`:

`Internal: ValueError: The model's max seq len (4096) is larger than the maximum number of tokens that can be stored in KV cache (624)`

I increased that to 95% in the `model.json` but still fails with same error. It mentions KV cache size too. 

I'm running on a dual RTX A6000 workstation (so 2 x 48GB) and we should be able to squeeze the 7B model in. However, I'm aware that you guys mentioned quantization during your talk but not aware what the parameter names etc are for this option. There was a flavor that this feature might be automatic? With quantization I can normally load the 70B variant without issues. Thank you for your help with this.

cheers

**Comment by IAINATDBI** [comment]
As a wild guess I tried "quantization":"gptq" in the model.json and it's now looking for a config file?

Cheers

**Comment by IAINATDBI** [comment]
Here's a shot of nvidia-smi just prior to the server shutting down.
![nvidia](https://github.com/triton-inference-server/triton_cli/assets/127157867/a351d5df-293e-4d2e-bc56-8eff56e0820e)

**Comment by rmccorm4** [comment]
Hey @IAINATDBI, can you open a separate issue to discuss the memory issues and quantization further if needed? 

To summarize a few quick points:
1. A 7B model should fit in GPU memory no problem with a 48GB even without quantization, so I'm assuming I need more details here on the model, config, etc. to reproduce.
2. For taking advantage of 2x GPUs or doing multi-gpu inference in general, I believe this will be fully controlled by the vLLM arguments provided in the config. Our `model.json` is just a representation of vLLM's [AsyncEngineArgs](https://github.com/vllm-project/vllm/blob/ad6eca408bc515391992db0f8becaa78e23d1150/vllm/engine/arg_utils.py#L13), so you probably need to try something like [tensor_parallel_size](https://github.com/vllm-project/vllm/blob/ad6eca408bc515391992db0f8becaa78e23d1150/vllm/engine/arg_utils.py#L27) to 2 for 2 GPUs. I haven't had a chance to test this myself yet. You can see how we initialize the vLLM engine from these args [here](https://github.com/triton-inference-server/vllm_backend/blob/c1c88fa7dfbebcd3198ada913e127304d5ff0b46/src/model.py#L122-L124). CC @oandreeva-nv for viz
3. For the `quantization` question, this is again just a vLLM detail that we passthrough to the vLLM APIs. So whatever documentation on vLLM side should apply here for those details. I believe there are also some pre-quantized models hosted on huggingface for popular models like Llama2 that may work directly as well. The quantization described in our GTC talk was based primarily around TensorRT-LLM.

**Comment by IAINATDBI** [comment]
Thanks @rmccorm4, Ill raise any further quant questions separately.

However for this thread, the only way I can get triton to start without failing (even with gpt2) on cuda memory issues (see above image (screenshot) with very large memory hungry stub) is to launch the docker, install triton-cli, load the model, start triton and then docker exec into the container (per #50 ) to issue an infer command. I've even tried it on a different machine.

Hope this helps.

**Comment by rmccorm4** [comment]
Hi @IAINATDBI ,

We added support for `llama-2-7b-chat` as well as `llama-3-8b` and `llama-3-8b-instruct` for both vLLM and TRT-LLM in the latest release associated with Triton 24.04, please check it out: https://github.com/triton-inference-server/triton_cli/releases/tag/0.0.7.

If you're seeing other issues, please raise a separate issue. Closing this issue based on the title about adding "chat" variant support.

**Comment by IAINATDBI** [comment]
Awesome! Thank you, looking forward to checking this out. Cheers.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
