### ISSUE TITLE
Tag 0.0.7 appears to have stopped working - AttributeError

### ISSUE THREAD

**Issue by IAINATDBI** [triton-inference-server/triton_cli#71]
Hi

When 0.0.7 was released I was able to successfully pull/run `24.04` from NGC, successfully build  the trtllm engine and inference using the llama-3-8b-instruct model.

Just tried it again and get the below error:

```
 triton infer -m llama-3-8b-instruct --prompt "machine learning is"
/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/service_pb2_grpc.py:21: RuntimeWarning: The grpc package installed is at version 1.60.1, but the generated code in grpc_service_pb2_grpc.py depends on grpcio>=1.64.0. Please upgrade your grpc module to grpcio>=1.64.0 or downgrade your generated code using grpcio-tools<=1.60.1. This warning will become an error in 1.65.0, scheduled for release on June 25, 2024.
  warnings.warn(
triton - ERROR - Channel.unary_unary() got an unexpected keyword argument '_registered_method'
Exception ignored in: <function InferenceServerClient.__del__ at 0x7efbea4eb250>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in __del__
    self.close()
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 264, in close
    self.stop_stream()
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 1811, in stop_stream
    if self._stream is not None:
AttributeError: 'InferenceServerClient' object has no attribute '_stream'
```

I did notice the following pip conflicts when installing requirements:

```
cudf 23.12.0 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
dask-cudf 23.12.0 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
```
Also when building trtllm backend, got following error in logs but did not halt building:

`triton - ERROR - [Errno 16] Device or resource busy: '/root/models'`

Report at end of trtllm build:

```
⠼ Building TRT-LLM engine for meta-llama/Meta-Llama-3-8B-Instruct...[06/07/2024-12:17:40] [TRT-LLM] [I] Serializing engine to /tmp/engines/llama-3-8b-instruct/rank0.engine...
⠙ Building TRT-LLM engine for meta-llama/Meta-Llama-3-8B-Instruct...[06/07/2024-12:17:51] [TRT-LLM] [I] Engine serialized. Total time: 00:00:10
⠏ Building TRT-LLM engine for meta-llama/Meta-Llama-3-8B-Instruct...[06/07/2024-12:17:51] [TRT-LLM] [I] Total time of building all engines: 00:00:36
triton - INFO - Current repo at /root/models:
models/
├── llama-3-8b-instruct/
│   ├── 1/
│   │   ├── lib/
│   │   │   ├── decode.py
│   │   │   └── triton_decoder.py
│   │   └── model.py
│   └── config.pbtxt
├── postprocessing/
│   ├── 1/
│   │   └── model.py
│   └── config.pbtxt
├── preprocessing/
│   ├── 1/
│   │   └── model.py
│   └── config.pbtxt
└── tensorrt_llm/
    ├── 1/
    └── config.pbtxt
```
   Following `triton start` :
```
    +---------------------+---------+--------+
| Model               | Version | Status |
+---------------------+---------+--------+
| llama-3-8b-instruct | 1       | READY  |
| postprocessing      | 1       | READY  |
| preprocessing       | 1       | READY  |
| tensorrt_llm        | 1       | READY  |
+---------------------+---------+--------+
```
```
I0607 13:12:29.264827 545 grpc_server.cc:2463] Started GRPCInferenceService at 0.0.0.0:8001
I0607 13:12:29.265065 545 http_server.cc:4692] Started HTTPService at 0.0.0.0:8000
I0607 13:12:29.306907 545 http_server.cc:362] Started Metrics Service at 0.0.0.0:8002
```
All looked ok, shelled into the container and tried to `triton infer....` and got the error at the start.

However, was successful in using `curl `approach and the model responded correctly.

Cheers

**Comment by KrishnanPrash** [comment]
Hello @IAINATDBI,

- I believe the `AttributeError` is being thrown by changes made by the `grpcio` package required by `tritonclient`.`tritonclient` generates stub code that requires `grpcio>=1.64.0` but it's requirements file has `grpcio>=1.41.0`. This loose dependency requirement has been addressed with a recent [pull request](https://github.com/triton-inference-server/triton_cli/pull/67). 
There are two possible solutions for this:
  1. A potential solution for now would be to remove the `GIT_REF` in this [step](https://github.com/triton-inference-server/triton_cli?tab=readme-ov-file#install-from-github) to get the fixed version of the `triton_cli`
  2. In `pyproject.toml`, change the requirements from `"tritonclient[all] == 2.45"` to `"tritonclient[all] >= 2.46"` and add `"grpcio>=1.64.0"`.
- We are aware of the `cudf` and `dask-cudf` pip conflicts and our best advice is to ignore it for the time being. 
-  For the following error, `triton - ERROR - [Errno 16] Device or resource busy: '/root/models'`, I was not able to re-create this issue, but would guess that an error occurred during a `triton import` or `triton remove` statement. In the past, I encountered this error when I mounted my models directory directly to the docker container (`-v .../models:.../models`), which made it impossible to delete the folder when I ran `triton remove`
